### ISSUE TITLE
mmap length is too large

### ISSUE THREAD

**Issue by JamesHabben** [PoorBillionaire/USN-Record-Carver#1]
I tried to be lazy and run this against a full dd image. Received the error "mmap length is too large" as a result. Expected?

**Comment by PoorBillionaire** [comment]
Thanks James - are you running the script with 32-bit Python by chance?

**Comment by JamesHabben** [comment]
Sure am. x64 system, but I have had lots of problems with using the x64 python.

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32

**Comment by PoorBillionaire** [comment]
Great, thanks. The address space available to the process is likely the culprit. The accepted answer in [this stackoverflow thread](http://stackoverflow.com/questions/14289421/how-to-use-mmap-in-python-when-the-whole-file-is-too-big) summarizes the problem and a solution nicely.

I'll test loading/unloading with different offsets and look at how that impacts performance. I'll have something for you in a couple days at the latest. My schedule has blown up in my face this week.

Thanks for letting me know!

**Comment by PoorBillionaire** [comment]
Also if you'd still like to try being lazy in the meantime, attempt it with 64-bit Python if you have that available :)

**Comment by JamesHabben** [comment]
Acceptable answer would also be "use the proper version, idiot"

**Comment by PoorBillionaire** [comment]
Hey James, apologies for the delay. I decided that for now, I will avoid unmapping and remapping the input file for the sake of simplicity.

Commit 684d36d6f7eacf6a585830a29b0bec18f5da6ae7 helps address this issue by providing an error message when Python is invoked with an available address space insufficient for the input file to be mapped:

_[ - ] ERROR: The running Python process does not present a large enough address space to accommodate memory mapping the intput file. Try switching to 64-bit Python._

Hope this helps!

--
Adam
